<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>chess_robot_bringup</name>
  <version>0.1.0</version>
  <description>Launch files for the chess robot workspace</description>
  <maintainer email="rokey@todo.todo">rokey</maintainer>
  <license>Apache-2.0</license>

  <depend>rclpy</depend>
  <depend>chess_pick_place</depend>
  <depend>chess_robot_motion</depend>

  <exec_depend>ros2launch</exec_depend>
  <exec_depend>dsr_bringup2</exec_depend>
  <exec_depend>realsense2_camera</exec_depend>
  <exec_depend>chess_vision_bringup</exec_depend>
  <exec_depend>chess_occupancy</exec_depend>
  <exec_depend>object_detection</exec_depend>
  <exec_depend>robot_control</exec_depend>
  <exec_depend>od_msg</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
